project_id = "cnamodabnlhlzvluvoja"

[api]
enabled = true
port = 54321

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[auth]
enabled = true
[auth.email]
enable_signup = true

[edge-runtime]
enabled = true
port = 54326