// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnamodabnlhlzvluvoja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuYW1vZGFibmxobHp2bHV2b2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODU0OTQsImV4cCI6MjA3MTk2MTQ5NH0.t8Shcf4UvaP7Meoh3oeW4XwAzyMsqfIjspeMslwSr3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});